#!/usr/bin/env bash
# Creates the DigitalOcean resources for OpenProject: a managed PostgreSQL cluster that only accepts
# this deployment's Droplets, a Droplet with Docker, and a cloud firewall. THIS SPENDS MONEY on the
# account doctl is logged in to.
#
# Prerequisites: doctl (`brew install doctl`, then `doctl auth init`), an SSH key uploaded to DigitalOcean.
# Usage: SSH_KEY_ID=<id or fingerprint> ./provision.sh
# Slugs are overridable; list valid ones with `doctl compute size list` and
# `doctl databases options slugs --engine pg`.
# Do not run this with `bash -x`: tracing would print the generated secrets.
set -euo pipefail

: "${SSH_KEY_ID:?set SSH_KEY_ID (see: doctl compute ssh-key list)}"
REGION="${REGION:-fra1}"
NAME="${NAME:-openproject}"
DROPLET_SIZE="${DROPLET_SIZE:-s-2vcpu-4gb}"      # enough for 20-30 people; resize on sustained swap or load > 2
DB_SIZE="${DB_SIZE:-db-s-1vcpu-1gb}"             # db-s-1vcpu-2gb raises the connection cap from 22 to 47
DB_VERSION="${DB_VERSION:-17}"
HERE="$(cd "$(dirname "$0")" && pwd)"
# The secrets file lives outside the repository so that no branch switch or `git add -A` can pick it up.
ENV_OUT="${ENV_OUT:-$HOME/.config/openproject-do/.env}"

[ ! -e "$ENV_OUT" ] || { echo "$ENV_OUT already exists. It holds the secrets of an existing deployment; move it away deliberately before provisioning again." >&2; exit 1; }
doctl compute ssh-key get "$SSH_KEY_ID" >/dev/null || { echo "SSH key $SSH_KEY_ID not found in this DigitalOcean account (doctl compute ssh-key list)." >&2; exit 1; }
if doctl databases list --format Name --no-header | grep -qx "${NAME}-db"; then
  echo "A database cluster named ${NAME}-db already exists. Refusing to create a duplicate." >&2; exit 1
fi

echo "==> This will create in ${REGION}: Droplet ${DROPLET_SIZE}, PostgreSQL ${DB_VERSION} ${DB_SIZE}, a firewall."
read -r -p "Type 'create' to continue: " answer
[ "$answer" = "create" ] || { echo "aborted"; exit 1; }

CREATED=""
on_exit() {
  status=$?
  if [ "$status" -ne 0 ] && [ -n "$CREATED" ]; then
    printf '\nprovision.sh failed. Billable resources created so far:\n%s\nDelete them (control panel or doctl) before retrying.\n' "$CREATED" >&2
  fi
}
trap on_exit EXIT

echo "==> Database cluster (takes about 5 minutes)"
doctl databases create "${NAME}-db" --engine pg --version "$DB_VERSION" --size "$DB_SIZE" \
  --region "$REGION" --num-nodes 1 --wait >/dev/null
DB_ID="$(doctl databases list --format ID,Name --no-header | awk -v n="${NAME}-db" '$2==n{print $1}')"
[ -n "$DB_ID" ] || { echo "could not find database ${NAME}-db after creating it" >&2; exit 1; }
CREATED="${CREATED}  database cluster ${DB_ID} (${NAME}-db)
"
echo "    database cluster ${DB_ID}"

echo "==> Restrict the database to Droplets tagged '${NAME}'"
# Tag-based, so a replacement Droplet created with the same tag gets access without another step.
doctl databases firewalls append "$DB_ID" --rule "tag:${NAME}" >/dev/null
doctl databases db create "$DB_ID" openproject >/dev/null

echo "==> Droplet"
DROPLET_ID="$(doctl compute droplet create "$NAME" --region "$REGION" --size "$DROPLET_SIZE" \
  --image ubuntu-24-04-x64 --ssh-keys "$SSH_KEY_ID" --enable-backups --enable-monitoring \
  --user-data-file "$HERE/cloud-init.yml" --tag-name "$NAME" --wait --format ID --no-header)"
CREATED="${CREATED}  droplet ${DROPLET_ID} (${NAME})
"
echo "    droplet ${DROPLET_ID}"
DROPLET_IP="$(doctl compute droplet get "$DROPLET_ID" --format PublicIPv4 --no-header)"

echo "==> Cloud firewall for Droplets tagged '${NAME}': SSH, HTTP, HTTPS in; everything out"
doctl compute firewall create --name "${NAME}-fw" --tag-names "$NAME" \
  --inbound-rules "protocol:tcp,ports:22,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:80,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:443,address:0.0.0.0/0,address:::/0 protocol:udp,ports:443,address:0.0.0.0/0,address:::/0" \
  --outbound-rules "protocol:tcp,ports:all,address:0.0.0.0/0,address:::/0 protocol:udp,ports:all,address:0.0.0.0/0,address:::/0 protocol:icmp,address:0.0.0.0/0,address:::/0" >/dev/null
CREATED="${CREATED}  firewall ${NAME}-fw
"

echo "==> Writing ${ENV_OUT} (mode 600; nothing secret is printed)"
mkdir -p "$(dirname "$ENV_OUT")"
chmod 700 "$(dirname "$ENV_OUT")"
umask 177
PRIVATE_URI="$(doctl databases connection "$DB_ID" --private --format URI --no-header)"
APP_URI="$(printf '%s' "$PRIVATE_URI" | sed -E 's#/defaultdb\?#/openproject?#')&pool=12"
case "$APP_URI" in */openproject\?*) ;; *) echo "unexpected database URI shape; fix DATABASE_URL in ${ENV_OUT} by hand" >&2 ;; esac
ADMIN_PW="$(openssl rand -base64 18)"
# Secrets are appended with printf rather than substituted with sed, so no character in a
# generated password can break the command.
grep -v -E '^(SECRET_KEY_BASE|DATABASE_URL|OPENPROJECT_SEED__ADMIN__USER__PASSWORD)=' "$HERE/.env.example" > "$ENV_OUT"
{
  printf '\n# Generated by provision.sh\n'
  printf 'SECRET_KEY_BASE=%s\n' "$(openssl rand -hex 64)"
  printf 'DATABASE_URL=%s\n' "$APP_URI"
  printf 'OPENPROJECT_SEED__ADMIN__USER__PASSWORD=%s\n' "$ADMIN_PW"
} >> "$ENV_OUT"

STATE_OUT="$(dirname "$ENV_OUT")/state"
{
  printf 'NAME=%s\n' "$NAME"
  printf 'DROPLET_ID=%s\n' "$DROPLET_ID"
  printf 'DROPLET_IP=%s\n' "$DROPLET_IP"
  printf 'DB_ID=%s\n' "$DB_ID"
} > "$STATE_OUT"

cat <<MSG

Done. Droplet ${DROPLET_ID} at ${DROPLET_IP}, database ${DB_ID}.
These facts are saved in ${STATE_OUT}, so nothing depends on this printout.

Next, from this directory (an agent can run all of these):
  make configure HOST=<host name> ADMIN_MAIL=<your address>     then create the DNS A record it names
  make image BUMP=minor                                         unless an image is already pinned
  make dns-wait
  make up

Then, in a terminal yourself:
  make admin-password        log in as admin once and set a new password
  make create-admin LOGIN=<not guessable> FIRST=.. LAST=.. MAIL=..
And back to the agent:
  make harden backup-install roles
MSG
