#!/usr/bin/env bash
# Creates the DigitalOcean resources for OpenProject: a VPC-private managed PostgreSQL cluster,
# a Droplet with Docker, and a cloud firewall. THIS SPENDS MONEY on the account doctl is logged in to.
#
# Prerequisites: doctl (`brew install doctl`, then `doctl auth init`), an SSH key uploaded to DigitalOcean.
# Usage: SSH_KEY_ID=<id or fingerprint> ./provision.sh
# Slugs are overridable; list valid ones with `doctl compute size list` and
# `doctl databases options slugs --engine pg`.
set -euo pipefail

: "${SSH_KEY_ID:?set SSH_KEY_ID (see: doctl compute ssh-key list)}"
REGION="${REGION:-fra1}"
NAME="${NAME:-openproject}"
DROPLET_SIZE="${DROPLET_SIZE:-s-2vcpu-4gb}"      # s-4vcpu-8gb once you pass ~20 active users
DB_SIZE="${DB_SIZE:-db-s-1vcpu-1gb}"             # db-s-1vcpu-2gb raises the connection cap from 22 to 47
DB_VERSION="${DB_VERSION:-17}"
HERE="$(cd "$(dirname "$0")" && pwd)"

echo "==> This will create in ${REGION}: Droplet ${DROPLET_SIZE}, PostgreSQL ${DB_VERSION} ${DB_SIZE}, a firewall."
read -r -p "Type 'create' to continue: " answer
[ "$answer" = "create" ] || { echo "aborted"; exit 1; }

echo "==> Database cluster (takes about 5 minutes)"
DB_ID="$(doctl databases create "${NAME}-db" --engine pg --version "$DB_VERSION" --size "$DB_SIZE" \
  --region "$REGION" --num-nodes 1 --wait --format ID --no-header)"
doctl databases db create "$DB_ID" openproject >/dev/null

echo "==> Droplet"
DROPLET_ID="$(doctl compute droplet create "$NAME" --region "$REGION" --size "$DROPLET_SIZE" \
  --image ubuntu-24-04-x64 --ssh-keys "$SSH_KEY_ID" --enable-backups --enable-monitoring \
  --user-data-file "$HERE/cloud-init.yml" --tag-name "$NAME" --wait --format ID --no-header)"
DROPLET_IP="$(doctl compute droplet get "$DROPLET_ID" --format PublicIPv4 --no-header)"

echo "==> Restrict the database to this Droplet"
doctl databases firewalls append "$DB_ID" --rule "droplet:${DROPLET_ID}" >/dev/null

echo "==> Cloud firewall: SSH, HTTP, HTTPS in; everything out"
doctl compute firewall create --name "${NAME}-fw" --droplet-ids "$DROPLET_ID" \
  --inbound-rules "protocol:tcp,ports:22,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:80,address:0.0.0.0/0,address:::/0 protocol:tcp,ports:443,address:0.0.0.0/0,address:::/0 protocol:udp,ports:443,address:0.0.0.0/0,address:::/0" \
  --outbound-rules "protocol:tcp,ports:all,address:0.0.0.0/0,address:::/0 protocol:udp,ports:all,address:0.0.0.0/0,address:::/0 protocol:icmp,address:0.0.0.0/0,address:::/0" >/dev/null

echo "==> Writing .env (secrets stay in this file, mode 600; nothing is printed)"
umask 177
PRIVATE_URI="$(doctl databases connection "$DB_ID" --private --format URI --no-header)"
APP_URI="$(printf '%s' "$PRIVATE_URI" | sed -E 's#/defaultdb\?#/openproject?#')&pool=12"
ADMIN_PW="$(openssl rand -base64 18)"
# Secrets are appended with printf rather than substituted with sed, so no character in a
# generated password can break the command.
grep -v -E '^(SECRET_KEY_BASE|DATABASE_URL|OPENPROJECT_SEED__ADMIN__USER__PASSWORD)=' "$HERE/.env.example" > "$HERE/.env"
{
  printf '\n# Generated by provision.sh\n'
  printf 'SECRET_KEY_BASE=%s\n' "$(openssl rand -hex 64)"
  printf 'DATABASE_URL=%s\n' "$APP_URI"
  printf 'OPENPROJECT_SEED__ADMIN__USER__PASSWORD=%s\n' "$ADMIN_PW"
} >> "$HERE/.env"

cat <<MSG

Done. Droplet ${DROPLET_ID} at ${DROPLET_IP}, database ${DB_ID}.

Next:
  1. Point a DNS A record for your host name at ${DROPLET_IP}.
  2. Edit ${HERE}/.env: set OPENPROJECT_HOST__NAME and the SMTP block. The initial admin password is in there too.
  3. Copy the stack to the server and start it:
       scp ${HERE}/{docker-compose.yml,Caddyfile,.env,bootstrap-db.sh,deploy.sh,backup.sh} root@${DROPLET_IP}:/srv/openproject/
       ssh root@${DROPLET_IP} 'cd /srv/openproject && ./bootstrap-db.sh && ./deploy.sh'
  4. Save SECRET_KEY_BASE from .env in your password manager.
MSG
